default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: iti
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: YallaNotlob_development

test:
  <<: *default
  database: YallaNotlob_test

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  username: <%=ENV['OPENSHIFT_MYSQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_MYSQL_DB_PASSWORD']%>
  host:   <%=ENV['OPENSHIFT_MYSQL_DB_HOST']%>
  port:   <%=ENV['OPENSHIFT_MYSQL_DB_PORT']%>

# development:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   pool: 5
#   database: <%=ENV['OPENSHIFT_APP_NAME']%>
#   username: <%=ENV['OPENSHIFT_MYSQL_DB_USERNAME']%>
#   password: <%=ENV['OPENSHIFT_MYSQL_DB_PASSWORD']%>
#   host:   <%=ENV['OPENSHIFT_MYSQL_DB_HOST']%>
#   port:   <%=ENV['OPENSHIFT_MYSQL_DB_PORT']%>
